name: Build and Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # Run for semantic version tags
    branches:
      - main      # Run for main branch (will create pre-releases)
  pull_request:
    branches:
      - main      # Run tests on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get all tags for versioning

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest build
          pip install -e .

      - name: Run tests
        run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for release creation
      id-token: write  # Needed for PyPI publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get all tags for versioning

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -e .

      - name: Build package
        run: |
          # Use our lib-version CLI to build the package with auto-versioning
          lib-version --package-dir .
          # List the built packages
          ls -la dist/

      - name: Get package version
        id: get_version
        run: |
          VERSION=$(lib-version --info | grep "Package version" | cut -d' ' -f3)
          echo "package_version=$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION"

      # For tagged releases (either v1.2 or v1.2.3 format)
      - name: Parse version and determine patch
        id: parse_version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Check if we need to auto-determine the patch version
          if [[ "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+$ ]]; then
            # Extract major.minor and determine patch
            MAJOR_MINOR=$(echo ${{ github.ref }} | sed -r 's|refs/tags/v([0-9]+\.[0-9]+)|\1|')
            MAJOR=$(echo $MAJOR_MINOR | cut -d. -f1)
            MINOR=$(echo $MAJOR_MINOR | cut -d. -f2)
            
            # Use new function to determine next patch version
            FULL_VERSION=$(lib-version --get-next-patch-version $MAJOR $MINOR)
            echo "Using auto-patched version: $FULL_VERSION"
          else
            # Regular semver tag, strip the 'v' prefix
            FULL_VERSION=$(echo ${{ github.ref }} | sed 's|refs/tags/v||')
            echo "Using explicit version: $FULL_VERSION"
          fi
          
          echo "full_version=$FULL_VERSION" >> $GITHUB_OUTPUT

      - name: Build package with determined version
        run: |
          # Use our lib-version CLI to build the package with specific version
          lib-version --package-dir . --version ${{ steps.parse_version.outputs.full_version }}
          # List the built packages
          ls -la dist/

      - name: Get bumped version
        id: get_bumped_version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Use our utility to get the bumped version
          BUMPED_VERSION=$(lib-version --bump-version ${{ steps.parse_version.outputs.full_version }})
          echo "bumped_version=$BUMPED_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped version: $BUMPED_VERSION"

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: v${{ steps.parse_version.outputs.full_version }}
          name: Release ${{ steps.parse_version.outputs.full_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new tag for bumped version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag v${{ steps.get_bumped_version.outputs.bumped_version }}
          git push origin v${{ steps.get_bumped_version.outputs.bumped_version }}

      # For non-tagged pushes to main (pre-releases)
      - name: Create Pre-release
        if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          prerelease: true
          tag_name: v${{ steps.get_version.outputs.package_version }}
          name: Pre-release ${{ steps.get_version.outputs.package_version }}