name: Build and Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # Run only for semantic version tags

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is needed to create releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required to fetch tags and full history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip build

    - name: Write version metadata
      run: |
        python scripts/write_version.py
        cat src/lib_version/version.json  # Debug output

    - name: Install the package in development mode
      run: pip install -e .

    - name: Build the package
      run: python -m build

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}